// vue-example/src/components/search/search.component.vue
<template>
	<div>
		<div class="md-layout md-gutter margin-bottom large">
			<div class="md-layout-item md-layout" v-if="result.artists && result.artists.length">
				<h1>Artists</h1>
				<div class="md-layout-item md-size-25 md-gutter md-layout margin-bottom" v-for="artist in result.artists" :key="artist.id">
					<router-link v-bind:to="'/artist/' + artist.id">
						<div class="md-layout-item md-size-50 md-gutter center">
							<img class="rounded margin-bottom" v-bind:src="'backend/artists/' + artist.img" />
						</div>
						<div class="md-layout-item center">
							{{artist.name}}
						</div>
					</router-link>
				</div>
			</div>
			<div class="md-layout-item md-layout" v-if="result.albums && result.albums.length">
				<h1>Albums</h1>
				<div class="md-layout-item md-size-25 md-gutter md-layout margin-bottom" v-for="album in result.albums" :key="album.id">
					<router-link v-bind:to="'/album/' + album.id">
						<div class="md-layout-item md-size-50 md-gutter center">
							<img class="rounded margin-bottom" v-bind:src="'backend/covers/' + album.coverImg" />
						</div>
						<div class="md-layout-item center">
							{{album.title}}
						</div>
					</router-link>
				</div>
			</div>
		</div>
		<div class="md-layout md-gutter">
			<div class="md-layout-item">
				<h1>Song results for '{{$route.query.phrase}}'</h1>
				<song-list-component v-bind:songs="result.songs"></song-list-component>
			</div>
		</div>
	</div>
</template>
<script src="./search.component.ts"></script>
<style src="./search.component.scss" scoped></style>

// react-example/src/components/search/search.component.tsx
import Grid from '@material-ui/core/Grid';
import { parse } from 'query-string';
import * as React from 'react';
import { Link } from 'react-router-dom';

import './search.component.scss';
import { MusicAgent } from '../../agents/music.agent';
import { HeaderToolbarService } from '../../services/header-toolbar.service';
import SongListComponent from '../song-list/song-list.component';
import { ISearchState } from './search-state.interface';

export default class SearchComponent extends React.Component<any, ISearchState> {
	private _unlistenLocation: () => void = null;

	public state: ISearchState = {
		phrase: '',
		result: {
			songs: [],
			albums: [],
			artists: []
		}
	}

	componentWillMount(): void {
		if (this.props.location.search) this.search(parse(this.props.location.search).phrase);

		this._unlistenLocation = this.props.history.listen(location => {
			if (location.search) this.search(parse(location.search).phrase);
		});
	}

	componentWillUnmount(): void {
		this._unlistenLocation();
		HeaderToolbarService.requestClearSearchPhrase();
	}

	private search(phrase: string) {
		MusicAgent.searchByPhrase(phrase).subscribe(result => {
			this.setState({ result, phrase });
		});
	}

	public render(): JSX.Element {
		return (
			<div id="search-component">
				<Grid spacing={32} container className="margin-bottom large">
					{this.state.result.artists && this.state.result.artists.length ? (
						<Grid item xs={true}>
							<Grid container>
								<h1>Artists</h1>
								{this.state.result.artists.map(artist => {
									return (
										<Grid item key={artist.id} xs={3} className="margin-bottom">
											<Grid container>
												<Link to={`/album/${artist.id}`}>
													<Grid item xs={6} className="center">
														<img className="rounded margin-bottom" src={`backend/artists/${artist.img}`} />
													</Grid>
													<Grid item className="center">
														{artist.name}
													</Grid>
												</Link>
											</Grid>
										</Grid>
									);
								})}
							</Grid>
						</Grid>
					) : ''}
					{this.state.result.albums && this.state.result.albums.length ? (
						<Grid item xs={true}>
							<Grid container>
								<h1>Albums</h1>
								{this.state.result.albums.map(album => {
									return (
										<Grid item key={album.id} xs={3} className="margin-bottom">
											<Grid container>
												<Link to={`/album/${album.id}`}>
													<Grid item xs={6} className="center">
														<img className="rounded margin-bottom" src={`backend/covers/${album.coverImg}`} />
													</Grid>
													<Grid item className="center">
														{album.title}
													</Grid>
												</Link>
											</Grid>
										</Grid>
									);
								})}
							</Grid>
						</Grid>
					) : ''}
				</Grid>
				<Grid container>
					<Grid item xs={true}>
						<h1>Song results for '{this.state.phrase}'</h1>
						<SongListComponent songs={this.state.result.songs}></SongListComponent>
					</Grid>
				</Grid>
			</div >
		);
	}
}
