// angular-example/src/app/components/song-list/song-list.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	Input,
	OnDestroy
} from '@angular/core';

import { ISong } from './../../contracts/song.interface';
import { FavoritesService } from './../../services/favorites.service';
import { MusicService } from './../../services/music.service';

@Component({
	selector: 'song-list-component',
	templateUrl: './song-list.component.html',
	styleUrls: ['./song-list.component.scss']
})
export class SongListComponent implements OnDestroy {
	private _subscriptions: Subscription[] = [];

	@Input() public songs!: ISong[];
	public currentSongPaused: boolean = false;
	public displayedColumns: string[] = ['play', 'favorite', 'title', 'artist', 'album'];
	public favorites: number[] = [];
	public playingSong: ISong = null;

	constructor(
		private _favoritesService: FavoritesService,
		private _musicService: MusicService
	) {
		this._subscriptions.push(this._musicService.currentlyPlayingSong.subscribe(playingSong => {
			this.playingSong = playingSong;
		}));

		this._subscriptions.push(this._musicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.currentSongPaused = currentSongPaused;
		}));

		this._subscriptions.push(this._favoritesService.favoritesChange.subscribe(favorites => {
			this.favorites = favorites;
		}));
	}

	public ngOnDestroy(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public playSong(song: ISong): void {
		if (this.playingSong && this.playingSong.id === song.id)
			this._musicService.resumeOrPauseCurrentSong();
		else
			this._musicService.playSong(song.id);
	}

	public playAll(): void {
		this._musicService.playCollection(this.songs);
	}

	public toggleFavorite(songId: number): void {
		this._favoritesService.toggleFavorite(songId);
	}
}
<div>
	<table mat-table
	       *ngIf="songs && songs.length"
	       [dataSource]="songs"
	       class="full-width">

		<ng-container matColumnDef="play">
			<th mat-header-cell
			    *matHeaderCellDef
			    class="thin overflow-visible relative">
				<button color="primary"
				        mat-raised-button
				        class="absolute"
				        (click)="playAll()">
					PLAY ALL
				</button>
			</th>
			<td mat-cell
			    *matCellDef="let song"
			    class="thin">
				<button mat-button
				        mat-icon-button
				        style="margin-left: 7px"
				        [class.active]="playingSong && playingSong.id === song.id"
				        (click)="playSong(song)">
					<mat-icon>{{playingSong && playingSong.id === song.id && !currentSongPaused ? 'pause_circle_outline' : 'play_circle_outline'}}</mat-icon>
				</button>
			</td>
		</ng-container>

		<ng-container matColumnDef="favorite">
			<th mat-header-cell
			    *matHeaderCellDef
			    class="thin"></th>
			<td mat-cell
			    *matCellDef="let song"
			    class="thin">
				<button mat-button
				        mat-icon-button
				        (click)="toggleFavorite(song.id)">
					<mat-icon>{{favorites.indexOf(song.id) === -1 ? 'star_border' : 'star'}}</mat-icon>
				</button>
			</td>
		</ng-container>

		<ng-container matColumnDef="title">
			<th mat-header-cell
			    *matHeaderCellDef>Title</th>
			<td mat-cell
			    *matCellDef="let song">{{song.title}}</td>
		</ng-container>

		<ng-container matColumnDef="artist">
			<th mat-header-cell
			    *matHeaderCellDef>Artist</th>
			<td mat-cell
			    *matCellDef="let song">
				<a [routerLink]="'/artist/' + song.artist.id">{{song.artist.name}}</a>
			</td>
		</ng-container>

		<ng-container matColumnDef="album">
			<th mat-header-cell
			    *matHeaderCellDef>Album</th>
			<td mat-cell
			    *matCellDef="let song">
				<a [routerLink]="'/album/' + song.album.id">{{song.album.title}}</a>
			</td>
		</ng-container>

		<tr mat-header-row
		    *matHeaderRowDef="displayedColumns"></tr>
		<tr mat-row
		    *matRowDef="let row; columns: displayedColumns;"></tr>
	</table>
	<div *ngIf="!songs || !songs.length">
		<h3 class="no-border">There are no results to show.</h3>
	</div>
</div>

// react-example/src/components/song-list/song-list.component.tsx
import { Subscription } from 'rxjs/Subscription';

import Paper from '@material-ui/core/Paper';
import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';
import * as React from 'react';
import { Link } from 'react-router-dom';

import './song-list.component.scss';
import Button from '../../../node_modules/@material-ui/core/Button';
import Icon from '../../../node_modules/@material-ui/core/Icon';
import IconButton from '../../../node_modules/@material-ui/core/IconButton';
import { ISong } from '../../contracts/song.interface';
import { FavoritesService } from './../../services/favorites.service';
import { MusicService } from './../../services/music.service';
import { ISongListProps } from './song-list-props.interface';
import { ISongListState } from './song-list-state.interface';

export default class SongListComponent extends React.Component<ISongListProps, ISongListState> {
	private _subscriptions: Subscription[] = [];

	public state: ISongListState = {
		currentSongPaused: false,
		favorites: [],
		playingSong: null
	}

	public componentWillMount(): void {
		this._subscriptions.push(MusicService.currentlyPlayingSong.subscribe(playingSong => {
			this.setState({ playingSong });
		}));

		this._subscriptions.push(MusicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.setState({ currentSongPaused });
		}));

		this._subscriptions.push(FavoritesService.favoritesChange.subscribe(favorites => {
			this.setState({ favorites });
		}));
	}

	public componentWillUnmount(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public playSong(song: ISong): void {
		if (this.state.playingSong && this.state.playingSong.id === song.id)
			MusicService.resumeOrPauseCurrentSong();
		else
			MusicService.playSong(song.id);
	}

	public playAll(): void {
		MusicService.playCollection(this.props.songs);
	}

	public toggleFavorite(songId: number): void {
		FavoritesService.toggleFavorite(songId);
	}

	public render(): JSX.Element {
		if (!this.props.songs || !this.props.songs.length) return <h3 className="no-border">There are no results to show.</h3>;
		return (
			<Paper className="song-list">
				<Table>
					<TableHead>
						<TableRow>
							<TableCell className="thin overflow-visible relative">
								<Button color="primary" variant="raised" className="absolute" onClick={() => this.playAll()}>PLAY ALL</Button>
							</TableCell>
							<TableCell className="thin"></TableCell>
							<TableCell>Title</TableCell>
							<TableCell>Artist</TableCell>
							<TableCell>Album</TableCell>
						</TableRow>
					</TableHead>
					<TableBody>
						{this.props.songs.map(song => {
							return (
								<TableRow key={song.id}>
									<TableCell className="thin">
										<IconButton className={`${this.state.playingSong && this.state.playingSong.id === song.id ? 'active' : ''}`} onClick={() => this.playSong(song)}>
											<Icon>{this.state.playingSong && this.state.playingSong.id === song.id && !this.state.currentSongPaused ? 'pause_circle_outline' : 'play_circle_outline'}</Icon>
										</IconButton>
									</TableCell>
									<TableCell className="thin">
										<IconButton onClick={() => this.toggleFavorite(song.id)}>
											<Icon>{this.state.favorites.indexOf(song.id) === -1 ? 'star_border' : 'star'}</Icon>
										</IconButton>
									</TableCell>
									<TableCell>{song.title}</TableCell>
									<TableCell><Link to={`/artist/${song.artist.id}`}>{song.artist.name}</Link></TableCell>
									<TableCell><Link to={`/album/${song.album.id}`}>{song.album.title}</Link></TableCell>
								</TableRow>
							);
						})}
					</TableBody>
				</Table>
			</Paper>
		);
	}
}
