// react-example/src/components/header-toolbar/header-toolbar.component.tsx
import { Subscription } from 'rxjs/Subscription';

import AppBar from '@material-ui/core/AppBar';
import Grid from '@material-ui/core/Grid';
import Icon from '@material-ui/core/Icon';
import IconButton from '@material-ui/core/IconButton';
import TextField from '@material-ui/core/TextField';
import Toolbar from '@material-ui/core/Toolbar';
import {
	parse,
	stringify
} from 'query-string';
import * as React from 'react';
import {
	Link,
	withRouter
} from 'react-router-dom';

import './header-toolbar.component.scss';
import { DrawerService } from '../../services/drawer.service';
import { HeaderToolbarService } from '../../services/header-toolbar.service';
import { IHeaderToolbarState } from './header-toolbar-state.interface';

class HeaderToolbarComponent extends React.Component<any, IHeaderToolbarState> {
	private _subscriptions: Subscription[] = [];

	public state: IHeaderToolbarState = {
		searchPhrase: ''
	}

	componentWillMount(): void {
		if (this.props.location.search) this.setState({ searchPhrase: parse(this.props.location.search).phrase });

		this._subscriptions.push(HeaderToolbarService.clearSearchPhrase.subscribe(() => {
			this.setState({ searchPhrase: '' });
		}));
	}

	componentWillUnmount(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public onSearch(event: React.ChangeEvent<HTMLInputElement>): void {
		this.setState({ searchPhrase: event.target.value });
		this.props.history.push({
			pathname: '/search',
			search: stringify({ phrase: event.target.value })
		});
	}

	public toggleNavDrawer(): void {
		DrawerService.toggleNavDrawer();
	}

	public render(): JSX.Element {
		return (
			<AppBar id="header-toolbar">
				<Toolbar>
					<Grid container>
						<Grid item xs={3}>
							<IconButton onClick={() => this.toggleNavDrawer()}>
								<Icon>menu</Icon>
							</IconButton>
							<Link to="/" className="button-link">
								<IconButton>
									<Icon>home</Icon>
								</IconButton>
							</Link>
						</Grid>
						<Grid item xs={5}>
							<TextField value={this.state.searchPhrase} onChange={(e) => this.onSearch(e)} placeholder="Search" fullWidth />
						</Grid>
						<Grid item xs={4} className="align-right">
							<IconButton>
								<Icon>language</Icon>
							</IconButton>
							<IconButton>
								<Icon>help</Icon>
							</IconButton>
							<IconButton>
								<Icon>account_circle</Icon>
							</IconButton>
						</Grid>
					</Grid>
				</Toolbar>
			</AppBar>
		);
	}
}

export default withRouter(HeaderToolbarComponent);

// angular-example/src/app/components/header-toolbar/header-toolbar.component.ts
import { Subscription } from 'rxjs';
import {
	filter,
	first
} from 'rxjs/operators';

import {
	Component,
	OnDestroy
} from '@angular/core';
import {
	ActivatedRoute,
	Router
} from '@angular/router';

import { DrawerService } from './../../services/drawer.service';
import { HeaderToolbarService } from './../../services/header-toolbar.service';

@Component({
	selector: 'header-toolbar-component',
	templateUrl: './header-toolbar.component.html',
	styleUrls: ['./header-toolbar.component.scss']
})
export class HeaderToolbarComponent implements OnDestroy {
	private _subscriptions: Subscription[] = [];

	public searchPhrase: string = '';

	constructor(
		private _drawerService: DrawerService,
		private _headerToolbarService: HeaderToolbarService,
		private _route: ActivatedRoute,
		private _router: Router
	) {
		this._subscriptions.push(this._route.queryParams.pipe(
			filter(params => !!params.phrase),
			first()
		).subscribe(params => {
			this.searchPhrase = params.phrase;
		}));

		this._subscriptions.push(this._headerToolbarService.clearSearchPhrase.subscribe(() => {
			this.searchPhrase = '';
		}));
	}

	public ngOnDestroy(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public toggleNavDrawer(): void {
		this._drawerService.toggleNavDrawer();
	}

	public onSearch(): void {
		this._router.navigate(['/search'], {
			queryParams: {
				phrase: this.searchPhrase
			}
		});
	}
}
<header>
	<mat-toolbar color="primary"
	             class="mat-elevation-z5">
		<div fxLayout
		     fxLayoutAlign="start center"
		     fxFill>
			<div fxFlex="25%">
				<button mat-button
				        (click)="toggleNavDrawer()"
				        class="mat-icon-button">
					<mat-icon>menu</mat-icon>
				</button>
				<a routerLink="/"
				   class="active">
					<button mat-button
					        class="mat-icon-button">
						<mat-icon>home</mat-icon>
					</button>
				</a>
			</div>
			<div fxFlex>
				<mat-form-field class="full-width">
					<input matInput
					       placeholder="Search"
					       (keyup)="onSearch()"
					       [(ngModel)]="searchPhrase" />
				</mat-form-field>
			</div>
			<div fxFlex="30%"
			     class="align-right">
				<button mat-button
				        class="mat-icon-button">
					<mat-icon>language</mat-icon>
				</button>
				<button mat-button
				        class="mat-icon-button">
					<mat-icon>help</mat-icon>
				</button>
				<button mat-button
				        class="mat-icon-button">
					<mat-icon>account_circle</mat-icon>
				</button>
			</div>
		</div>
	</mat-toolbar>
</header>
