// react-example/src/components/nav-drawer/nav-drawer.component.tsx
import { Subscription } from 'rxjs/Subscription';

import Drawer from '@material-ui/core/Drawer';
import Icon from '@material-ui/core/Icon';
import * as React from 'react';
import { NavLink } from 'react-router-dom';

import './nav-drawer.component.scss';
import { StorageItems } from '../../enums/storage-items.enum';
import { DrawerService } from '../../services/drawer.service';
import { StorageService } from '../../services/storage.service';
import { INavDrawerState } from './nav-drawer-state.interface';

export default class NavDrawerComponent extends React.Component<undefined, INavDrawerState> {
	private _subscriptions: Subscription[] = [];
	public state: INavDrawerState = {
		show: true
	}

	public componentWillMount(): void {
		this._subscriptions.push(DrawerService.navDrawerOpen.subscribe(open => {
			if (this.state.show !== open) this.setState({ show: open });
			StorageService.set(StorageItems.DrawerOpen, open);
		}));

		this._subscriptions.push(DrawerService.navDrawerToggle.subscribe(() => {
			DrawerService.toggleNavDrawer(!this.state.show);
		}));
	}

	public componentWillUnmount(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public render(): JSX.Element {
		return (
			<Drawer id="nav-drawer" variant="persistent" open={this.state.show}>
				<div className="menu-links">
					<NavLink to="/favorites">
						<Icon>star</Icon> Favorites
					</NavLink>
					<NavLink to="/playlists">
						<Icon>playlist_play</Icon> Playlists
					</NavLink>
				</div>
			</Drawer>
		);
	}
}

// vue-example/src/components/nav-drawer/nav-drawer.component.ts
import { Subscription } from 'rxjs/Subscription';

import {
	Component,
	Vue
} from 'vue-property-decorator';

import { StorageItems } from '../../enums/storage-items.enum';
import { DrawerService } from '../../services/drawer.service';
import { StorageService } from '../../services/storage.service';

@Component
export default class NavDrawerComponent extends Vue {
	subscriptions: Subscription[] = [];
	show: boolean = true;

	created() {
		this.subscriptions.push(DrawerService.navDrawerOpen.subscribe(open => {
			if (this.show !== open) this.show = open;
			StorageService.set(StorageItems.DrawerOpen, open);
		}));

		this.subscriptions.push(DrawerService.navDrawerToggle.subscribe(() => {
			this.show = !this.show;
			DrawerService.toggleNavDrawer(this.show);
			StorageService.set(StorageItems.DrawerOpen, this.show);
		}));
	}

	beforeDestroy() {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}
}
