// angular-example/src/app/components/player/player.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	ElementRef,
	OnDestroy,
	ViewChild
} from '@angular/core';

import { ISongMetadata } from './../../contracts/song-metadata.interface';
import { ISong } from './../../contracts/song.interface';
import { ITime } from './../../contracts/time.interface';
import { TimeFormatter } from './../../formatters/time.formatter';
import { FavoritesService } from './../../services/favorites.service';
import { MusicService } from './../../services/music.service';

@Component({
	selector: 'player-component',
	templateUrl: './player.component.html',
	styleUrls: ['./player.component.scss']
})
export class PlayerComponent implements OnDestroy {
	@ViewChild('timeEl') timeEl: ElementRef<HTMLElement>;
	@ViewChild('volumeEl') volumeEl: ElementRef<HTMLElement>;

	public currentSongPaused: boolean = false;
	public currentTime: ITime = null;
	public chosenSong: ISong = null;
	public playingSongMetadata: ISongMetadata = null;
	public progressValue: number = 0;
	public skipTimeChange: boolean = false;
	public subscriptions: Subscription[] = [];
	public volumeValue: number = 100;
	public isFavorite: boolean = false;
	public isPlayingCollection: boolean = false;
	public isRepeatingCollection: boolean = false;
	public isShufflingCollection: boolean = false;

	constructor(
		private _favoritesService: FavoritesService,
		private _musicService: MusicService
	) {
		this.subscriptions.push(this._musicService.currentlyChosenSong.subscribe(chosenSong => {
			this.chosenSong = chosenSong;
			if (this.chosenSong) this.isFavorite = this._favoritesService.isFavorite(this.chosenSong.id);
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongMetadata.subscribe(playingSongMetadata => {
			this.playingSongMetadata = playingSongMetadata;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongTimeChange.subscribe(currentTime => {
			if (this.skipTimeChange) return;
			this.currentTime = currentTime;
			this.progressValue = this.currentTime && this.playingSongMetadata ? this.currentTime.raw / this.playingSongMetadata.time.raw * 100 : 0;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongVolumeChange.subscribe(volumeValue => {
			this.volumeValue = volumeValue * 100;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.currentSongPaused = currentSongPaused;
		}));

		this.subscriptions.push(this._musicService.isPlayingCollection.subscribe(isPlayingCollection => {
			this.isPlayingCollection = isPlayingCollection;
		}));

		this.subscriptions.push(this._musicService.isRepeatingCollection.subscribe(isRepeatingCollection => {
			this.isRepeatingCollection = isRepeatingCollection;
		}));

		this.subscriptions.push(this._musicService.isShufflingCollection.subscribe(isShufflingCollection => {
			this.isShufflingCollection = isShufflingCollection;
		}));

		this.subscriptions.push(this._favoritesService.favoritesChange.subscribe(() => {
			if (this.chosenSong) this.isFavorite = this._favoritesService.isFavorite(this.chosenSong.id);
		}));
	}

	public ngOnDestroy(): void {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}

	public changeProgress(event): void {
		const rect: ClientRect = this.timeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this.progressValue = progress * 100;
		this.currentTime = TimeFormatter.formatTime(this.playingSongMetadata.time.raw * progress);
	}

	public changeTime(event): void {
		const rect: ClientRect = this.timeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this._musicService.changeCurrentTime(this.playingSongMetadata.time.raw * progress);
	}

	public requestCurrentTime(): void {
		this._musicService.emitCurrentTime();
	}

	public changeVolumeDisplayValue(event): void {
		const rect: ClientRect = this.volumeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this.volumeValue = progress * 100;
	}

	public setVolume(event): void {
		const rect: ClientRect = this.volumeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this._musicService.setVolume(progress);
	}

	public requestVolume(): void {
		this._musicService.emitVolume();
	}

	public toggleMute(): void {
		this._musicService.setVolume(this.volumeValue < 1 ? 1 : 0);
	}

	public playOrPause(): void {
		this._musicService.resumeOrPauseCurrentSong();
	}

	public playNext(): void {
		this._musicService.playNextFromCollection();
	}

	public playPrev(): void {
		this._musicService.playPrevFromCollection();
	}

	public shuffle(): void {
		this._musicService.setShuffleCollection(!this.isShufflingCollection);
	}

	public repeat(): void {
		this._musicService.setRepeatCollection(!this.isRepeatingCollection);
	}

	public toggleFavorite(): void {
		this._favoritesService.toggleFavorite(this.chosenSong.id);
	}

	public close(): void {
		this._musicService.reset();
	}
}
<mat-toolbar *ngIf="chosenSong">
	<div fxLayout
	     fxLayoutAlign="start center"
	     fxFill>
		<div fxFlex="25%"
		     class="song-details">
			<img [src]="'backend/covers/' + chosenSong.album.coverImg"
			     class="pull-left" />
			<div>
				<a [routerLink]="'/album/' + chosenSong.album.id">
					<b>{{chosenSong.title}}</b>
				</a>
			</div>
			<div>
				<a [routerLink]="'/artist/' + chosenSong.artist.id">{{chosenSong.artist.name}}</a>
			</div>
			<button mat-button
			        class="mat-icon-button"
			        (click)="toggleFavorite()">
				<mat-icon>{{isFavorite ? 'star' : 'star_border'}}</mat-icon>
			</button>
		</div>
		<div fxFlex>
			<div fxLayout
			     fxLayoutAlign="start center"
			     fxFill
			     class="controls">
				<div fxFlex
				     class="align-center">
					<button mat-button
					        class="mat-icon-button"
					        [class.active]="isShufflingCollection"
					        [disabled]="!isPlayingCollection"
					        (click)="shuffle()">
						<mat-icon>shuffle</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button"
					        [disabled]="!isPlayingCollection"
					        (click)="playPrev()">
						<mat-icon>skip_previous</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button md-size-2x"
					        (click)="playOrPause()">
						<mat-icon style="font-size: 46px; margin-left: -20px"
						          class="md-size-2x">{{currentSongPaused ? 'play_circle_outline' : 'pause_circle_outline'}}</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button"
					        [disabled]="!isPlayingCollection"
					        (click)="playNext()">
						<mat-icon>skip_next</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button"
					        [class.active]="isRepeatingCollection"
					        [disabled]="!isPlayingCollection"
					        (click)="repeat()">
						<mat-icon>repeat</mat-icon>
					</button>
				</div>
			</div>
			<div fxLayoutAlign="start center"
			     fxFill>
				<div fxFlex="10%"
				     class="align-right">
					<div *ngIf="currentTime">
						{{currentTime.minutes}}:{{currentTime.seconds.toString().padStart(2, '0')}}
					</div>
				</div>
				<div fxFlex
				     class="progress">
					<div #timeEl
					     (click)="changeTime($event)"
					     (mouseenter)="skipTimeChange = true"
					     (mouseleave)="skipTimeChange = false; requestCurrentTime()"
					     (mousemove)="changeProgress($event)">
						<mat-progress-bar mode="determinate"
						                  [value]="progressValue">
						</mat-progress-bar>
					</div>
				</div>
				<div fxFlex="10%">
					<div *ngIf="playingSongMetadata">
						{{playingSongMetadata.time.minutes}}:{{playingSongMetadata.time.seconds.toString().padStart(2, '0')}}
					</div>
				</div>
			</div>
		</div>
		<div fxFlex="5"></div>
		<div fxFlex="5"
		     class="volume-button align-right">
			<button mat-button
			        class="mat-icon-button"
			        (click)="toggleMute()">
				<mat-icon>{{volumeValue > 50 ? 'volume_up' : volumeValue > 10 ? 'volume_down' : volumeValue > 1 ? 'volume_mute' : 'volume_off'}}</mat-icon>
			</button>
		</div>
		<div fxFlex="10%"
		     class="volume">
			<div #volumeEl
			     (click)="setVolume($event)"
			     (mousemove)="changeVolumeDisplayValue($event)"
			     (mouseleave)="requestVolume()">
				<mat-progress-bar mode="determinate"
				                  [value]="volumeValue">
				</mat-progress-bar>
			</div>
		</div>
		<div fxFlex="5%"
		     class="align-right close">
			<button mat-button
			        class="mat-icon-button"
			        (click)="close()">
				<mat-icon>close</mat-icon>
			</button>
		</div>
	</div>
</mat-toolbar>

// react-example/src/components/player/player.component.tsx
import { Subscription } from 'rxjs/Subscription';

import AppBar from '@material-ui/core/AppBar';
import Grid from '@material-ui/core/Grid';
import Icon from '@material-ui/core/Icon';
import IconButton from '@material-ui/core/IconButton';
import LinearProgress from '@material-ui/core/LinearProgress';
import Toolbar from '@material-ui/core/Toolbar';
import * as React from 'react';
import { Link } from 'react-router-dom';

import './player.component.scss';
import { TimeFormatter } from '../../formatters/time.formatter';
import { FavoritesService } from '../../services/favorites.service';
import { MusicService } from '../../services/music.service';
import { IPlayerState } from './player-state.interface';

export default class PlayerComponent extends React.Component<undefined, IPlayerState> {
	private _skipTimeChange: boolean = false;
	private _subscriptions: Subscription[] = [];

	public state: IPlayerState = {
		chosenSong: null,
		currentSongPaused: false,
		currentTime: null,
		isFavorite: false,
		isPlayingCollection: false,
		isRepeatingCollection: false,
		isShufflingCollection: false,
		playingSongMetadata: null,
		progressValue: 0,
		volumeValue: 100
	};
	public progressRef: React.RefObject<HTMLDivElement> = React.createRef();
	public volumeRef: React.RefObject<HTMLDivElement> = React.createRef();

	componentWillMount() {
		this._subscriptions.push(MusicService.currentlyChosenSong.subscribe(chosenSong => {
			this.setState({ chosenSong });
			if (chosenSong) this.setState({ isFavorite: FavoritesService.isFavorite(chosenSong.id) });
		}));

		this._subscriptions.push(MusicService.currentlyPlayingSongMetadata.subscribe(playingSongMetadata => {
			this.setState({ playingSongMetadata });
		}));

		this._subscriptions.push(MusicService.currentlyPlayingSongTimeChange.subscribe(currentTime => {
			if (this._skipTimeChange) return;
			this.setState({ currentTime, progressValue: currentTime && this.state.playingSongMetadata ? currentTime.raw / this.state.playingSongMetadata.time.raw * 100 : 0 })
		}));

		this._subscriptions.push(MusicService.currentlyPlayingSongVolumeChange.subscribe(volumeValue => {
			this.setState({ volumeValue: volumeValue * 100 })
		}));

		this._subscriptions.push(MusicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.setState({ currentSongPaused });
		}));

		this._subscriptions.push(MusicService.isPlayingCollection.subscribe(isPlayingCollection => {
			this.setState({ isPlayingCollection });
		}));

		this._subscriptions.push(MusicService.isRepeatingCollection.subscribe(isRepeatingCollection => {
			this.setState({ isRepeatingCollection });
		}));

		this._subscriptions.push(MusicService.isShufflingCollection.subscribe(isShufflingCollection => {
			this.setState({ isShufflingCollection });
		}));

		this._subscriptions.push(FavoritesService.favoritesChange.subscribe(() => {
			if (this.state.chosenSong) this.setState({ isFavorite: FavoritesService.isFavorite(this.state.chosenSong.id) });
		}));
	}

	componentWillUnmount() {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public changeProgress(event): void {
		const rect: ClientRect = this.progressRef.current.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this.setState({ progressValue: progress * 100, currentTime: TimeFormatter.formatTime(this.state.playingSongMetadata.time.raw * progress) });
	}

	public changeTime(event): void {
		const rect: ClientRect = this.progressRef.current.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		MusicService.changeCurrentTime(this.state.playingSongMetadata.time.raw * progress);
	}

	public requestCurrentTime(): void {
		MusicService.emitCurrentTime();
	}

	public changeVolumeDisplayValue(event): void {
		const rect: ClientRect = this.volumeRef.current.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this.setState({ volumeValue: progress * 100 });
	}

	public setVolume(event): void {
		const rect: ClientRect = this.volumeRef.current.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		MusicService.setVolume(progress);
	}

	public requestVolume(): void {
		MusicService.emitVolume();
	}

	public toggleMute(): void {
		MusicService.setVolume(this.state.volumeValue < 1 ? 1 : 0);
	}

	public playOrPause(): void {
		MusicService.resumeOrPauseCurrentSong();
	}

	public playNext(): void {
		MusicService.playNextFromCollection();
	}

	public playPrev(): void {
		MusicService.playPrevFromCollection();
	}

	public shuffle(): void {
		MusicService.setShuffleCollection(!this.state.isShufflingCollection);
	}

	public repeat(): void {
		MusicService.setRepeatCollection(!this.state.isRepeatingCollection);
	}

	public toggleFavorite(): void {
		FavoritesService.toggleFavorite(this.state.chosenSong.id);
	}

	public close(): void {
		MusicService.reset();
	}

	public render(): JSX.Element {
		if (!this.state.chosenSong) return null;
		return (
			<AppBar id="player">
				<Toolbar>
					<Grid container>
						<Grid item xs={3} className="song-details">
							<img src={`backend/covers/${this.state.chosenSong.album.coverImg}`} className="pull-left" />
							<div><Link to={`/album/${this.state.chosenSong.album.id}`}><b>{this.state.chosenSong.title}</b></Link></div>
							<div><Link to={`/artist/${this.state.chosenSong.artist.id}`}>{this.state.chosenSong.artist.name}</Link></div>
							<IconButton onClick={() => this.toggleFavorite()}>
								<Icon>{this.state.isFavorite ? 'star' : 'star_border'}</Icon>
							</IconButton>
						</Grid>
						<Grid item xs={6}>
							<Grid container className="controls">
								<Grid item xs={12} className="align-center">
									<IconButton disabled={!this.state.isPlayingCollection} className={`${this.state.isShufflingCollection ? 'active' : ''}`} onClick={() => this.shuffle()}>
										<Icon>shuffle</Icon>
									</IconButton>
									<IconButton disabled={!this.state.isPlayingCollection} onClick={() => this.playPrev()}>
										<Icon>skip_previous</Icon>
									</IconButton>
									<IconButton onClick={() => this.playOrPause()}>
										<Icon style={{ fontSize: '48px' }}>{this.state.currentSongPaused ? 'play_circle_outline' : 'pause_circle_outline'}</Icon>
									</IconButton>
									<IconButton disabled={!this.state.isPlayingCollection} onClick={() => this.playNext()}>
										<Icon>skip_next</Icon>
									</IconButton>
									<IconButton disabled={!this.state.isPlayingCollection} className={`${this.state.isRepeatingCollection ? 'active' : ''}`} onClick={() => this.repeat()}>
										<Icon>repeat</Icon>
									</IconButton>
								</Grid>
							</Grid>
							<Grid container className="controls">
								<Grid item xs={1} className="align-right" style={{ fontSize: '14px' }}>
									{this.state.currentTime ? `${this.state.currentTime.minutes}:${(this.state.currentTime.seconds.toString()).padStart(2, '0')}` : ''}
								</Grid>
								<Grid item xs={10} className="progress">
									<div ref={this.progressRef} onClick={(e) => this.changeTime(e)} onMouseEnter={() => this._skipTimeChange = true} onMouseLeave={() => { this._skipTimeChange = false; this.requestCurrentTime() }} onMouseMove={(e) => this.changeProgress(e)} >
										<LinearProgress className="range" variant="determinate" value={this.state.progressValue}></LinearProgress>
									</div>
								</Grid>
								<Grid item xs={1} style={{ fontSize: '14px' }}>
									{this.state.playingSongMetadata ? `${this.state.playingSongMetadata.time.minutes}:${(this.state.playingSongMetadata.time.seconds.toString()).padStart(2, '0')}` : ''}
								</Grid>
							</Grid>
						</Grid>
						<Grid item xs={3}>
							<Grid container>
								<Grid item xs={2}></Grid>
								<Grid item xs={3} className="align-right volume-button">
									<IconButton onClick={() => this.toggleMute()}>
										<Icon>{this.state.volumeValue < 1 ? 'volume_off' : this.state.volumeValue < 10 ? 'volume_mute' : this.state.volumeValue < 50 ? 'volume_down' : 'volume_up'}}</Icon>
									</IconButton>
								</Grid>
								<Grid item xs={5} className="volume">
									<div ref={this.volumeRef} onClick={(e) => this.setVolume(e)} onMouseMove={(e) => this.changeVolumeDisplayValue(e)} onMouseLeave={() => this.requestVolume()}>
										<LinearProgress className="range" variant="determinate" value={this.state.volumeValue}></LinearProgress>
									</div>
								</Grid>
								<Grid item xs={2} className="align-right close">
									<IconButton onClick={() => this.close()}>
										<Icon>close</Icon>
									</IconButton>
								</Grid>
							</Grid>
						</Grid>
					</Grid>
				</Toolbar>
			</AppBar>
		);
	};
}
