// vue-example/src/components/home/home.component.ts
import { Subscription } from 'rxjs/Subscription';

import {
	Component,
	Vue
} from 'vue-property-decorator';

import { MusicAgent } from '../../agents/music.agent';
import { ISong } from '../../contracts/song.interface';
import { MusicService } from '../../services/music.service';

@Component
export default class HomeComponent extends Vue {
	currentSongPaused: boolean = false;
	playingSong: ISong = null;
	subscriptions: Subscription[] = [];
	suggestedSongs: ISong[] = [];

	created(): void {
		this.refreshSuggested();

		this.subscriptions.push(MusicService.currentlyPlayingSong.subscribe(playingSong => {
			this.playingSong = playingSong;
		}));

		this.subscriptions.push(MusicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.currentSongPaused = currentSongPaused;
		}));
	}

	beforeDestroy() {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}

	refreshSuggested(): void {
		MusicAgent.getSuggested().subscribe(suggestedSongs => {
			this.suggestedSongs = suggestedSongs;
		});
	}

	playSong(song: ISong): void {
		if (this.playingSong && this.playingSong.id === song.id)
			MusicService.resumeOrPauseCurrentSong();
		else
			MusicService.playSong(song.id);
	}
}

// angular-example/src/app/components/home/home.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	OnDestroy
} from '@angular/core';

import { MusicAgent } from './../../agents/music.agent';
import { ISong } from './../../contracts/song.interface';
import { MusicService } from './../../services/music.service';

@Component({
	templateUrl: './home.component.html',
	styleUrls: ['home.component.scss']
})
export class HomeComponent implements OnDestroy {
	public currentSongPaused: boolean = false;
	public playingSong: ISong = null;
	public subscriptions: Subscription[] = [];
	public suggestedSongs: ISong[] = [];

	constructor(
		private _musicAgent: MusicAgent,
		private _musicService: MusicService
	) {
		this.refreshSuggested();

		this.subscriptions.push(this._musicService.currentlyPlayingSong.subscribe(playingSong => {
			this.playingSong = playingSong;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.currentSongPaused = currentSongPaused;
		}));
	}

	public ngOnDestroy(): void {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}

	public refreshSuggested(): void {
		this._musicAgent.getSuggested().subscribe(suggestedSongs => {
			this.suggestedSongs = suggestedSongs;
		});
	}

	public playSong(song: ISong): void {
		if (this.playingSong && this.playingSong.id === song.id)
			this._musicService.resumeOrPauseCurrentSong();
		else
			this._musicService.playSong(song.id);
	}
}
<div>
	<h1>Home</h1>
	<p>There are millions of songs. Play your favorites, discover new tracks, and build the perfect collection. You'll find readymade playlists to match your mood, put together by music fans and experts. Hear this week's latest singles and albums, and check out what's hot in the Top 50. There are millions of songs. Play your favorites, discover new tracks, and build the perfect collection. You'll find readymade playlists to match your mood, put together by music fans and experts. Hear this week's latest singles and albums, and check out what's hot in the Top 50.</p>

	<h2>
		<span>
			Personalized music for you
			<button mat-button
			        class="mat-icon-button"
			        (click)="refreshSuggested()">
				<mat-icon>refresh</mat-icon>
			</button>
		</span>
	</h2>
	<ul xLayout="row"
	    fxLayoutAlign="start"
	    fxFill
	    id="suggested-songs">
		<li *ngFor="let song of suggestedSongs"
		    fxFlex="25%">
			<div class="img-wrapper"
			     [class.active]="playingSong && playingSong.id === song.id"
			     (click)="playSong(song)">
				<img [src]="'backend/covers/' + song.album.coverImg" />
				<mat-icon class="mat-size-3x">{{playingSong && playingSong.id === song.id && !currentSongPaused ? 'pause_circle_filled' : 'play_circle_filled'}}</mat-icon>
			</div>
			<div class="details">
				<div class="title">
					<a [routerLink]="'/album/' + song.album.id">
						<b>{{song.title}}</b>
					</a>
				</div>
				<div class="artist">
					<a [routerLink]="'/artist/' + song.artist.id">{{song.artist.name}}</a>
				</div>
			</div>
		</li>
	</ul>
</div>
