// vue-example/src/components/favorites/favorites.component.ts
import { Subscription } from 'rxjs/Subscription';

import {
	Component,
	Vue
} from 'vue-property-decorator';

import { MusicAgent } from '../../agents/music.agent';
import { ISong } from '../../contracts/song.interface';
import { FavoritesService } from '../../services/favorites.service';
import SongListComponent from '../song-list/song-list.component.vue';

@Component({
	components: {
		SongListComponent
	}
})
export default class FavoritesComponent extends Vue {
	songs: ISong[] = [];
	subscriptions: Subscription[] = [];

	created(): void {
		this.subscriptions.push(FavoritesService.favoritesChange.subscribe(favorites => {
			MusicAgent.getSongsById(favorites).subscribe(songs => {
				this.songs = songs;
			});
		}));
	}

	beforeDestroy() {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}
}

// angular-example/src/app/components/favorites/favorites.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	OnDestroy
} from '@angular/core';

import { MusicAgent } from './../../agents/music.agent';
import { ISong } from './../../contracts/song.interface';
import { FavoritesService } from './../../services/favorites.service';

@Component({
	templateUrl: './favorites.component.html'
})
export class FavoritesComponent implements OnDestroy {
	private _subscriptions: Subscription[] = [];

	public songs: ISong[] = [];

	constructor(
		private _favoritesService: FavoritesService,
		private _musicAgent: MusicAgent
	) {
		this._subscriptions.push(this._favoritesService.favoritesChange.subscribe(favorites => {
			this._musicAgent.getSongsById(favorites).subscribe(songs => {
				this.songs = songs;
			});
		}));
	}

	public ngOnDestroy(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}
}
<div>
	<h1>Favorite songs</h1>
	<song-list-component [songs]="songs"></song-list-component>
</div>
