// react-example/src/components/album/album.component.tsx
import 'rxjs/add/observable/forkJoin';
import { Observable } from 'rxjs/Observable';

import Grid from '@material-ui/core/Grid';
import * as React from 'react';

import { AlbumAgent } from '../../agents/album.agent';
import SongListComponent from '../song-list/song-list.component';
import { IAlbumState } from './album-state.interface';

export default class AlbumComponent extends React.Component<any, IAlbumState> {
	public state: IAlbumState = {
		album: null,
		songs: []
	}

	componentWillMount(): void {
		const albumId: number = +this.props.match.params.id;

		Observable.forkJoin([
			AlbumAgent.getById(albumId),
			AlbumAgent.getSongsByArtistId(albumId)
		]).subscribe(result => {
			this.setState({ album: result[0], songs: result[1] });
		});
	}

	public render(): JSX.Element {
		return (
			<Grid container spacing={24}>
				{this.state.album ?
					(
						<Grid item xs={3}>
							<img src={`backend/covers/${this.state.album.coverImg}`} />
							<h3 className="no-border">
								{this.state.album.title}
							</h3>
						</Grid>
					) : ''
				}
				{this.state.songs.length ?
					(
						<Grid item xs={9}>
							<SongListComponent songs={this.state.songs}></SongListComponent>
						</Grid>
					) : ''

				}
			</Grid >
		);
	}
}

// angular-example/src/app/components/album/album.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { AlbumAgent } from './../../agents/album.agent';
import { IAlbum } from './../../contracts/album.interface';
import { ISong } from './../../contracts/song.interface';

@Component({
	templateUrl: './album.component.html'
})
export class AlbumComponent {
	public album: IAlbum = null;
	public songs: ISong[] = [];

	constructor(
		private _albumAgent: AlbumAgent,
		private _route: ActivatedRoute
	) {
		const albumId: number = +this._route.snapshot.params.id;

		this._albumAgent.getById(albumId).subscribe(album => {
			this.album = album;
		});

		this._albumAgent.getSongsByAlbumId(albumId).subscribe(songs => {
			this.songs = songs;
		});
	}
}
<div fxLayout
     fxFill
     fxLayoutGap="15px">
	<div *ngIf="album"
	     fxFlex="25%">
		<img [src]="'backend/covers/' + album.coverImg" />
		<h3 class="no-border">
			{{album.title}}
		</h3>
	</div>
	<div *ngIf="songs && songs.length"
	     fxFlex>
		<song-list-component [songs]="songs"></song-list-component>
	</div>
</div>
