// angular-example/src/app/components/album/album.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { AlbumAgent } from './../../agents/album.agent';
import { IAlbum } from './../../contracts/album.interface';
import { ISong } from './../../contracts/song.interface';

@Component({
	templateUrl: './album.component.html'
})
export class AlbumComponent {
	public album: IAlbum = null;
	public songs: ISong[] = [];

	constructor(
		private _albumAgent: AlbumAgent,
		private _route: ActivatedRoute
	) {
		const albumId: number = +this._route.snapshot.params.id;

		this._albumAgent.getById(albumId).subscribe(album => {
			this.album = album;
		});

		this._albumAgent.getSongsByAlbumId(albumId).subscribe(songs => {
			this.songs = songs;
		});
	}
}
<div fxLayout
     fxFill
     fxLayoutGap="15px">
	<div *ngIf="album"
	     fxFlex="25%">
		<img [src]="'backend/covers/' + album.coverImg" />
		<h3 class="no-border">
			{{album.title}}
		</h3>
	</div>
	<div *ngIf="songs && songs.length"
	     fxFlex>
		<song-list-component [songs]="songs"></song-list-component>
	</div>
</div>

// vue-example/src/components/album/album.component.ts
import {
	Component,
	Vue
} from 'vue-property-decorator';

import { AlbumAgent } from '../../agents/album.agent';
import { IAlbum } from '../../contracts/album.interface';
import { ISong } from '../../contracts/song.interface';
import SongListComponent from '../song-list/song-list.component.vue';

@Component({
	components: {
		SongListComponent
	}
})
export default class AlbumComponent extends Vue {
	album: IAlbum = null;
	songs: ISong[] = [];

	created() {
		const albumId: number = +this.$route.params.id;

		AlbumAgent.getById(albumId).subscribe(album => {
			this.album = album;
		});

		AlbumAgent.getSongsByArtistId(albumId).subscribe(songs => {
			this.songs = songs;
		});
	}
}
