// vue-example/src/components/artist/artist.component.ts
import {
	Component,
	Vue
} from 'vue-property-decorator';

import { ArtistAgent } from '../../agents/artist.agent';
import { IArtist } from '../../contracts/artist.interface';
import { ISong } from '../../contracts/song.interface';
import SongListComponent from '../song-list/song-list.component.vue';

@Component({
	components: {
		SongListComponent
	}
})
export default class ArtistComponent extends Vue {
	artist: IArtist = null;
	songs: ISong[] = [];

	created() {
		const artistId: number = +this.$route.params.id;

		ArtistAgent.getById(artistId).subscribe(artist => {
			this.artist = artist;
		});

		ArtistAgent.getSongsByArtistId(artistId).subscribe(songs => {
			this.songs = songs;
		});
	}
}

// angular-example/src/app/components/artist/artist.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ArtistAgent } from './../../agents/artist.agent';
import { IArtist } from './../../contracts/artist.interface';
import { ISong } from './../../contracts/song.interface';

@Component({
	templateUrl: './artist.component.html'
})
export class ArtistComponent {
	public artist: IArtist = null;
	public songs: ISong[] = [];

	constructor(
		private _artistAgent: ArtistAgent,
		private _route: ActivatedRoute
	) {
		const artistId: number = +this._route.snapshot.params.id;

		this._artistAgent.getById(artistId).subscribe(artist => {
			this.artist = artist;
		});

		this._artistAgent.getSongsByArtistId(artistId).subscribe(songs => {
			this.songs = songs;
		});
	}
}
<div fxLayout
     fxFill
     fxLayoutGap="15px">
	<div *ngIf="artist"
	     fxFlex="25%">
		<img [src]="'backend/artists/' + artist.img" />
		<h3 class="no-border">
			{{artist.name}}
		</h3>
	</div>
	<div *ngIf="songs && songs.length"
	     fxFlex>
		<song-list-component [songs]="songs"></song-list-component>
	</div>
</div>
