// react-example/src/components/search/search.component.tsx
import Grid from '@material-ui/core/Grid';
import { parse } from 'query-string';
import * as React from 'react';
import { Link } from 'react-router-dom';

import './search.component.scss';
import { MusicAgent } from '../../agents/music.agent';
import { HeaderToolbarService } from '../../services/header-toolbar.service';
import SongListComponent from '../song-list/song-list.component';
import { ISearchState } from './search-state.interface';

export default class SearchComponent extends React.Component<any, ISearchState> {
	private _unlistenLocation: () => void = null;

	public state: ISearchState = {
		phrase: '',
		result: {
			songs: [],
			albums: [],
			artists: []
		}
	}

	componentWillMount(): void {
		if (this.props.location.search) this.search(parse(this.props.location.search).phrase);

		this._unlistenLocation = this.props.history.listen(location => {
			if (location.search) this.search(parse(location.search).phrase);
		});
	}

	componentWillUnmount(): void {
		this._unlistenLocation();
		HeaderToolbarService.requestClearSearchPhrase();
	}

	private search(phrase: string) {
		MusicAgent.searchByPhrase(phrase).subscribe(result => {
			this.setState({ result, phrase });
		});
	}

	public render(): JSX.Element {
		return (
			<div id="search-component">
				<Grid spacing={32} container className="margin-bottom large">
					{this.state.result.artists && this.state.result.artists.length ? (
						<Grid item xs={true}>
							<Grid container>
								<h1>Artists</h1>
								{this.state.result.artists.map(artist => {
									return (
										<Grid item key={artist.id} xs={3} className="margin-bottom">
											<Grid container>
												<Link to={`/album/${artist.id}`}>
													<Grid item xs={6} className="center">
														<img className="rounded margin-bottom" src={`backend/artists/${artist.img}`} />
													</Grid>
													<Grid item className="center">
														{artist.name}
													</Grid>
												</Link>
											</Grid>
										</Grid>
									);
								})}
							</Grid>
						</Grid>
					) : ''}
					{this.state.result.albums && this.state.result.albums.length ? (
						<Grid item xs={true}>
							<Grid container>
								<h1>Albums</h1>
								{this.state.result.albums.map(album => {
									return (
										<Grid item key={album.id} xs={3} className="margin-bottom">
											<Grid container>
												<Link to={`/album/${album.id}`}>
													<Grid item xs={6} className="center">
														<img className="rounded margin-bottom" src={`backend/covers/${album.coverImg}`} />
													</Grid>
													<Grid item className="center">
														{album.title}
													</Grid>
												</Link>
											</Grid>
										</Grid>
									);
								})}
							</Grid>
						</Grid>
					) : ''}
				</Grid>
				<Grid container>
					<Grid item xs={true}>
						<h1>Song results for '{this.state.phrase}'</h1>
						<SongListComponent songs={this.state.result.songs}></SongListComponent>
					</Grid>
				</Grid>
			</div >
		);
	}
}

// angular-example/src/app/components/search/search.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	OnDestroy
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { MusicAgent } from './../../agents/music.agent';
import { ISearchResult } from './../../contracts/search-result.interface';
import { HeaderToolbarService } from './../../services/header-toolbar.service';

@Component({
	templateUrl: './search.component.html',
	styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnDestroy {
	private _subscriptions: Subscription[] = [];

	public result: ISearchResult = { songs: [], artists: [], albums: [] };

	constructor(
		private _headerToolbarService: HeaderToolbarService,
		private _route: ActivatedRoute,
		private _musicAgent: MusicAgent
	) {
		this._subscriptions.push(this._route.queryParams.subscribe(params => {
			this.search(params.phrase);
		}));
	}

	public ngOnDestroy(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
		this._headerToolbarService.requestClearSearchPhrase();
	}

	public search(phrase: string): void {
		this._musicAgent.searchByPhrase(phrase).subscribe(result => {
			this.result = result;
		});
	}
}
<div>
	<div fxLayout
	     fxFill
	     fxLayoutGap="20px"
	     class="margin-bottom large">
		<div fxFlex
		     *ngIf="result.artists && result.artists.length">
			<h1>Artists</h1>
			<div fxLayout="row wrap">
				<div fxFlex="25%"
				     class="margin-bottom"
				     *ngFor="let artist of result.artists">
					<a [routerLink]="'/artist/' + artist.id"
					   class="center">
						<div>
							<img class="rounded margin-bottom"
							     [src]="'backend/artists/' + artist.img" />
						</div>
						<div>
							{{artist.name}}
						</div>
					</a>
				</div>
			</div>
		</div>
		<div fxFlex
		     *ngIf="result.albums && result.albums.length">
			<h1>Albums</h1>
			<div fxLayout="row wrap">
				<div fxFlex="25%"
				     class="margin-bottom"
				     *ngFor="let album of result.albums">
					<a [routerLink]="'/album/' + album.id"
					   class="center">
						<div>
							<img class="rounded margin-bottom"
							     [src]="'backend/covers/' + album.coverImg" />
						</div>
						<div>
							{{album.title}}
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div fxLayout
	     fxFill>
		<div fxFlex>
			<h1>Songs</h1>
			<song-list-component [songs]="result.songs"></song-list-component>
		</div>
	</div>
</div>
