// angular-example/src/app/components/home/home.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	OnDestroy
} from '@angular/core';

import { MusicAgent } from './../../agents/music.agent';
import { ISong } from './../../contracts/song.interface';
import { MusicService } from './../../services/music.service';

@Component({
	templateUrl: './home.component.html',
	styleUrls: ['home.component.scss']
})
export class HomeComponent implements OnDestroy {
	public currentSongPaused: boolean = false;
	public playingSong: ISong = null;
	public subscriptions: Subscription[] = [];
	public suggestedSongs: ISong[] = [];

	constructor(
		private _musicAgent: MusicAgent,
		private _musicService: MusicService
	) {
		this.refreshSuggested();

		this.subscriptions.push(this._musicService.currentlyPlayingSong.subscribe(playingSong => {
			this.playingSong = playingSong;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.currentSongPaused = currentSongPaused;
		}));
	}

	public ngOnDestroy(): void {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}

	public refreshSuggested(): void {
		this._musicAgent.getSuggested().subscribe(suggestedSongs => {
			this.suggestedSongs = suggestedSongs;
		});
	}

	public playSong(song: ISong): void {
		if (this.playingSong && this.playingSong.id === song.id)
			this._musicService.resumeOrPauseCurrentSong();
		else
			this._musicService.playSong(song.id);
	}
}
<div>
	<h1>Home</h1>
	<p>There are millions of songs. Play your favorites, discover new tracks, and build the perfect collection. You'll find readymade playlists to match your mood, put together by music fans and experts. Hear this week's latest singles and albums, and check out what's hot in the Top 50. There are millions of songs. Play your favorites, discover new tracks, and build the perfect collection. You'll find readymade playlists to match your mood, put together by music fans and experts. Hear this week's latest singles and albums, and check out what's hot in the Top 50.</p>

	<h2>
		<span>
			Personalized music for you
			<button mat-button
			        class="mat-icon-button"
			        (click)="refreshSuggested()">
				<mat-icon>refresh</mat-icon>
			</button>
		</span>
	</h2>
	<ul xLayout="row"
	    fxLayoutAlign="start"
	    fxFill
	    id="suggested-songs">
		<li *ngFor="let song of suggestedSongs"
		    fxFlex="25%">
			<div class="img-wrapper"
			     [class.active]="playingSong && playingSong.id === song.id"
			     (click)="playSong(song)">
				<img [src]="'backend/covers/' + song.album.coverImg" />
				<mat-icon class="mat-size-3x">{{playingSong && playingSong.id === song.id && !currentSongPaused ? 'pause_circle_filled' : 'play_circle_filled'}}</mat-icon>
			</div>
			<div class="details">
				<div class="title">
					<a [routerLink]="'/album/' + song.album.id">
						<b>{{song.title}}</b>
					</a>
				</div>
				<div class="artist">
					<a [routerLink]="'/artist/' + song.artist.id">{{song.artist.name}}</a>
				</div>
			</div>
		</li>
	</ul>
</div>

// react-example/src/components/home/home.component.tsx
import { Subscription } from 'rxjs/Subscription';

import Grid from '@material-ui/core/Grid';
import Icon from '@material-ui/core/Icon';
import IconButton from '@material-ui/core/IconButton';
import * as React from 'react';
import { Link } from 'react-router-dom';

import './home.component.scss';
import { MusicAgent } from '../../agents/music.agent';
import { ISong } from '../../contracts/song.interface';
import { MusicService } from '../../services/music.service';
import { IHomeState } from './home-state.interface';

export default class HomeComponent extends React.Component<undefined, IHomeState> {
	private _subscriptions: Subscription[] = [];

	public state: IHomeState = {
		currentSongPaused: false,
		playingSong: null,
		suggestedSongs: []
	}

	componentWillMount(): void {
		this.refreshSuggested();

		this._subscriptions.push(MusicService.currentlyPlayingSong.subscribe(playingSong => {
			this.setState({ playingSong });
		}));

		this._subscriptions.push(MusicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.setState({ currentSongPaused });
		}));
	}

	componentWillUnmount(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public refreshSuggested(): void {
		MusicAgent.getSuggested().subscribe(suggestedSongs => {
			this.setState({ suggestedSongs })
		});
	}

	public playSong(song: ISong): void {
		if (this.state.playingSong && this.state.playingSong.id === song.id)
			MusicService.resumeOrPauseCurrentSong();
		else
			MusicService.playSong(song.id);
	}

	public render(): JSX.Element {
		return (
			<div id="home-component">
				<h1>Home</h1>
				<p>There are millions of songs. Play your favorites, discover new tracks, and build the perfect collection.
				You'll find readymade playlists to match your mood, put together by music fans and experts.
				Hear this week's latest singles and albums, and check out what's hot in the Top 50. There are millions of songs. Play your favorites, discover new tracks, and build the perfect collection.
				You'll find readymade playlists to match your mood, put together by music fans and experts.
				Hear this week's latest singles and albums, and check out what's hot in the Top 50.</p>

				<h2>
					<span className="title">
						Personalized music for you
						<IconButton onClick={() => this.refreshSuggested()}>
							<Icon>refresh</Icon>
						</IconButton>
					</span>
				</h2>

				<Grid container id="suggested-songs" spacing={24}>
					{this.state.suggestedSongs.map(song => {
						return (
							<Grid key={song.id} item xs={3}>
								<div onClick={() => this.playSong(song)} className={`img-wrapper ${this.state.playingSong && this.state.playingSong.id === song.id ? 'active' : ''}`}>
									<img src={`backend/covers/${song.album.coverImg}`} />
									<Icon style={{ fontSize: '72px' }}>{this.state.playingSong && this.state.playingSong.id === song.id && !this.state.currentSongPaused ? 'pause_circle_filled' : 'play_circle_filled'}</Icon>
								</div>
								<div className="details">
									<div className="title">
										<Link to={`/album/${song.album.id}`}>{song.title}</Link>
									</div>
									<div className="artist">
										<Link to={`/artist/${song.artist.id}`}>{song.artist.name}</Link>
									</div>
								</div>
							</Grid>
						);
					})}
				</Grid>
			</div>
		);
	}
}
