// angular-example/src/app/components/player/player.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	ElementRef,
	OnDestroy,
	ViewChild
} from '@angular/core';

import { ISongMetadata } from './../../contracts/song-metadata.interface';
import { ISong } from './../../contracts/song.interface';
import { ITime } from './../../contracts/time.interface';
import { TimeFormatter } from './../../formatters/time.formatter';
import { FavoritesService } from './../../services/favorites.service';
import { MusicService } from './../../services/music.service';

@Component({
	selector: 'player-component',
	templateUrl: './player.component.html',
	styleUrls: ['./player.component.scss']
})
export class PlayerComponent implements OnDestroy {
	@ViewChild('timeEl') timeEl: ElementRef<HTMLElement>;
	@ViewChild('volumeEl') volumeEl: ElementRef<HTMLElement>;

	public currentSongPaused: boolean = false;
	public currentTime: ITime = null;
	public chosenSong: ISong = null;
	public playingSongMetadata: ISongMetadata = null;
	public progressValue: number = 0;
	public skipTimeChange: boolean = false;
	public subscriptions: Subscription[] = [];
	public volumeValue: number = 100;
	public isFavorite: boolean = false;
	public isPlayingCollection: boolean = false;
	public isRepeatingCollection: boolean = false;
	public isShufflingCollection: boolean = false;

	constructor(
		private _favoritesService: FavoritesService,
		private _musicService: MusicService
	) {
		this.subscriptions.push(this._musicService.currentlyChosenSong.subscribe(chosenSong => {
			this.chosenSong = chosenSong;
			if (this.chosenSong) this.isFavorite = this._favoritesService.isFavorite(this.chosenSong.id);
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongMetadata.subscribe(playingSongMetadata => {
			this.playingSongMetadata = playingSongMetadata;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongTimeChange.subscribe(currentTime => {
			if (this.skipTimeChange) return;
			this.currentTime = currentTime;
			this.progressValue = this.currentTime && this.playingSongMetadata ? this.currentTime.raw / this.playingSongMetadata.time.raw * 100 : 0;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongVolumeChange.subscribe(volumeValue => {
			this.volumeValue = volumeValue * 100;
		}));

		this.subscriptions.push(this._musicService.currentlyPlayingSongPaused.subscribe(currentSongPaused => {
			this.currentSongPaused = currentSongPaused;
		}));

		this.subscriptions.push(this._musicService.isPlayingCollection.subscribe(isPlayingCollection => {
			this.isPlayingCollection = isPlayingCollection;
		}));

		this.subscriptions.push(this._musicService.isRepeatingCollection.subscribe(isRepeatingCollection => {
			this.isRepeatingCollection = isRepeatingCollection;
		}));

		this.subscriptions.push(this._musicService.isShufflingCollection.subscribe(isShufflingCollection => {
			this.isShufflingCollection = isShufflingCollection;
		}));

		this.subscriptions.push(this._favoritesService.favoritesChange.subscribe(() => {
			if (this.chosenSong) this.isFavorite = this._favoritesService.isFavorite(this.chosenSong.id);
		}));
	}

	public ngOnDestroy(): void {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}

	public changeProgress(event): void {
		const rect: ClientRect = this.timeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this.progressValue = progress * 100;
		this.currentTime = TimeFormatter.formatTime(this.playingSongMetadata.time.raw * progress);
	}

	public changeTime(event): void {
		const rect: ClientRect = this.timeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this._musicService.changeCurrentTime(this.playingSongMetadata.time.raw * progress);
	}

	public requestCurrentTime(): void {
		this._musicService.emitCurrentTime();
	}

	public changeVolumeDisplayValue(event): void {
		const rect: ClientRect = this.volumeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this.volumeValue = progress * 100;
	}

	public setVolume(event): void {
		const rect: ClientRect = this.volumeEl.nativeElement.getBoundingClientRect();
		const progress = (event.pageX - rect.left) / rect.width;
		this._musicService.setVolume(progress);
	}

	public requestVolume(): void {
		this._musicService.emitVolume();
	}

	public toggleMute(): void {
		this._musicService.setVolume(this.volumeValue < 1 ? 1 : 0);
	}

	public playOrPause(): void {
		this._musicService.resumeOrPauseCurrentSong();
	}

	public playNext(): void {
		this._musicService.playNextFromCollection();
	}

	public playPrev(): void {
		this._musicService.playPrevFromCollection();
	}

	public shuffle(): void {
		this._musicService.setShuffleCollection(!this.isShufflingCollection);
	}

	public repeat(): void {
		this._musicService.setRepeatCollection(!this.isRepeatingCollection);
	}

	public toggleFavorite(): void {
		this._favoritesService.toggleFavorite(this.chosenSong.id);
	}

	public close(): void {
		this._musicService.reset();
	}
}
<mat-toolbar *ngIf="chosenSong">
	<div fxLayout
	     fxLayoutAlign="start center"
	     fxFill>
		<div fxFlex="25%"
		     class="song-details">
			<img [src]="'backend/covers/' + chosenSong.album.coverImg"
			     class="pull-left" />
			<div>
				<a [routerLink]="'/album/' + chosenSong.album.id">
					<b>{{chosenSong.title}}</b>
				</a>
			</div>
			<div>
				<a [routerLink]="'/artist/' + chosenSong.artist.id">{{chosenSong.artist.name}}</a>
			</div>
			<button mat-button
			        class="mat-icon-button"
			        (click)="toggleFavorite()">
				<mat-icon>{{isFavorite ? 'star' : 'star_border'}}</mat-icon>
			</button>
		</div>
		<div fxFlex>
			<div fxLayout
			     fxLayoutAlign="start center"
			     fxFill
			     class="controls">
				<div fxFlex
				     class="align-center">
					<button mat-button
					        class="mat-icon-button"
					        [class.active]="isShufflingCollection"
					        [disabled]="!isPlayingCollection"
					        (click)="shuffle()">
						<mat-icon>shuffle</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button"
					        [disabled]="!isPlayingCollection"
					        (click)="playPrev()">
						<mat-icon>skip_previous</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button md-size-2x"
					        (click)="playOrPause()">
						<mat-icon style="font-size: 46px; margin-left: -20px"
						          class="md-size-2x">{{currentSongPaused ? 'play_circle_outline' : 'pause_circle_outline'}}</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button"
					        [disabled]="!isPlayingCollection"
					        (click)="playNext()">
						<mat-icon>skip_next</mat-icon>
					</button>
					<button mat-button
					        class="mat-icon-button"
					        [class.active]="isRepeatingCollection"
					        [disabled]="!isPlayingCollection"
					        (click)="repeat()">
						<mat-icon>repeat</mat-icon>
					</button>
				</div>
			</div>
			<div fxLayoutAlign="start center"
			     fxFill>
				<div fxFlex="10%"
				     class="align-right">
					<div *ngIf="currentTime">
						{{currentTime.minutes}}:{{currentTime.seconds.toString().padStart(2, '0')}}
					</div>
				</div>
				<div fxFlex
				     class="progress">
					<div #timeEl
					     (click)="changeTime($event)"
					     (mouseenter)="skipTimeChange = true"
					     (mouseleave)="skipTimeChange = false; requestCurrentTime()"
					     (mousemove)="changeProgress($event)">
						<mat-progress-bar mode="determinate"
						                  [value]="progressValue">
						</mat-progress-bar>
					</div>
				</div>
				<div fxFlex="10%">
					<div *ngIf="playingSongMetadata">
						{{playingSongMetadata.time.minutes}}:{{playingSongMetadata.time.seconds.toString().padStart(2, '0')}}
					</div>
				</div>
			</div>
		</div>
		<div fxFlex="5"></div>
		<div fxFlex="5"
		     class="volume-button align-right">
			<button mat-button
			        class="mat-icon-button"
			        (click)="toggleMute()">
				<mat-icon>{{volumeValue > 50 ? 'volume_up' : volumeValue > 10 ? 'volume_down' : volumeValue > 1 ? 'volume_mute' : 'volume_off'}}</mat-icon>
			</button>
		</div>
		<div fxFlex="10%"
		     class="volume">
			<div #volumeEl
			     (click)="setVolume($event)"
			     (mousemove)="changeVolumeDisplayValue($event)"
			     (mouseleave)="requestVolume()">
				<mat-progress-bar mode="determinate"
				                  [value]="volumeValue">
				</mat-progress-bar>
			</div>
		</div>
		<div fxFlex="5%"
		     class="align-right close">
			<button mat-button
			        class="mat-icon-button"
			        (click)="close()">
				<mat-icon>close</mat-icon>
			</button>
		</div>
	</div>
</mat-toolbar>

// vue-example/src/components/player/player.component.vue
<template>
	<md-toolbar v-if="chosenSong">
		<div class="md-layout">
			<div class="md-layout-item md-size-25 song-details">
				<img v-bind:src="'backend/covers/' + chosenSong.album.coverImg" class="pull-left" />
				<div><router-link v-bind:to="'/album/' + chosenSong.album.id"><b>{{chosenSong.title}}</b></router-link></div>
				<div><router-link v-bind:to="'/artist/' + chosenSong.artist.id">{{chosenSong.artist.name}}</router-link></div>
				<md-button class="md-icon-button" @click="toggleFavorite()">
					<md-icon>{{isFavorite ? 'star' : 'star_border'}}</md-icon>
				</md-button>
			</div>
			<div class="md-layout-item">
				<div class="md-layout controls">
					<div class="md-layout-item align-center">
						<md-button class="md-icon-button" :disabled="!isPlayingCollection" :active="isShufflingCollection" @click="shuffle">
							<md-icon>shuffle</md-icon>
						</md-button>
						<md-button class="md-icon-button" :disabled="!isPlayingCollection" @click="playPrev">
							<md-icon>skip_previous</md-icon>
						</md-button>
						<md-button class="md-icon-button md-size-2x" @click="playOrPause">
							<md-icon class="md-size-2x">{{currentSongPaused ? 'play_circle_outline' : 'pause_circle_outline'}}</md-icon>
						</md-button>
						<md-button class="md-icon-button" :disabled="!isPlayingCollection" @click="playNext">
							<md-icon>skip_next</md-icon>
						</md-button>
						<md-button class="md-icon-button" :disabled="!isPlayingCollection" :active="isRepeatingCollection" @click="repeat">
							<md-icon>repeat</md-icon>
						</md-button>
					</div>
				</div>
				<div class="md-layout">
					<div class="md-layout-item md-size-10 align-right">
						<div v-if="currentTime">
							{{currentTime.minutes}}:{{currentTime.seconds.toString().padStart(2, '0')}}
						</div>
					</div>
					<div class="md-layout-item progress">
						<div v-on:click="changeTime" v-on:mouseenter="skipTimeChange = true" v-on:mouseleave="skipTimeChange = false; requestCurrentTime()" v-on:mousemove="changeProgress" >
							<md-progress-bar md-mode="determinate" :md-value="progressValue"></md-progress-bar>
						</div>
					</div>
					<div class="md-layout-item md-size-10">
						<div v-if="playingSongMetadata">
							{{playingSongMetadata.time.minutes}}:{{playingSongMetadata.time.seconds.toString().padStart(2, '0')}}
						</div>
					</div>
				</div>
			</div>
			<div class="md-layout-item md-size-5"></div>
			<div class="md-layout-item md-size-5 volume-button align-right">
				<md-button class="md-icon-button" @click="toggleMute">
					<md-icon>{{volumeValue < 1 ? 'volume_off' : volumeValue < 10 ? 'volume_mute' : volumeValue < 50 ? 'volume_down' : 'volume_up' }}</md-icon>
				</md-button>
			</div>
			<div class="md-layout-item md-size-10 volume">
				<div v-on:click="setVolume" v-on:mousemove="changeVolumeDisplayValue" v-on:mouseleave="requestVolume()">
					<md-progress-bar md-mode="determinate" :md-value="volumeValue"></md-progress-bar>
				</div>
			</div>
			<div class="md-layout-item md-size-5 align-right close">
				<md-button class="md-icon-button" @click="close">
					<md-icon>close</md-icon>
				</md-button>
			</div>
		</div>
	</md-toolbar>
</template>
<script src="./player.component.ts"></script>
<style src="./player.component.scss" scoped></style>
