// angular-example/src/app/components/nav-drawer/nav-drawer.component.ts
import { Subscription } from 'rxjs';

import {
	Component,
	OnDestroy
} from '@angular/core';

import { StorageItems } from './../../enums/storage-items.enum';
import { DrawerService } from './../../services/drawer.service';
import { StorageService } from './../../services/storage.service';

@Component({
	selector: 'nav-drawer-component',
	templateUrl: './nav-drawer.component.html',
	styleUrls: ['./nav-drawer.component.scss']
})
export class NavDrawerComponent implements OnDestroy {
	private _subscriptions: Subscription[] = [];

	public show: boolean = true;

	constructor(
		private _drawerService: DrawerService,
		private _storageService: StorageService
	) {
		this._subscriptions.push(this._drawerService.navDrawerOpen.subscribe(open => {
			if (this.show !== open) this.show = open;
			this._storageService.set(StorageItems.DrawerOpen, open);
		}));

		this._subscriptions.push(this._drawerService.navDrawerToggle.subscribe(() => {
			this._drawerService.toggleNavDrawer(!this.show);
		}));
	}

	public ngOnDestroy(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}
}
<mat-drawer-container>
	<mat-drawer [opened]="show"
	            mode="side">
		<div class="menu-links">
			<a routerLink="/favorites"
			   routerLinkActive="active">
				<mat-icon>star</mat-icon> Favorites
			</a>
			<a routerLink="/playlists"
			   routerLinkActive="active">
				<mat-icon>playlist_play</mat-icon> Playlists
			</a>
		</div>
	</mat-drawer>
</mat-drawer-container>

// react-example/src/components/nav-drawer/nav-drawer.component.tsx
import { Subscription } from 'rxjs/Subscription';

import Drawer from '@material-ui/core/Drawer';
import Icon from '@material-ui/core/Icon';
import * as React from 'react';
import { NavLink } from 'react-router-dom';

import './nav-drawer.component.scss';
import { StorageItems } from '../../enums/storage-items.enum';
import { DrawerService } from '../../services/drawer.service';
import { StorageService } from '../../services/storage.service';
import { INavDrawerState } from './nav-drawer-state.interface';

export default class NavDrawerComponent extends React.Component<undefined, INavDrawerState> {
	private _subscriptions: Subscription[] = [];
	public state: INavDrawerState = {
		show: true
	}

	public componentWillMount(): void {
		this._subscriptions.push(DrawerService.navDrawerOpen.subscribe(open => {
			if (this.state.show !== open) this.setState({ show: open });
			StorageService.set(StorageItems.DrawerOpen, open);
		}));

		this._subscriptions.push(DrawerService.navDrawerToggle.subscribe(() => {
			DrawerService.toggleNavDrawer(!this.state.show);
		}));
	}

	public componentWillUnmount(): void {
		this._subscriptions.forEach(sub => sub.unsubscribe());
	}

	public render(): JSX.Element {
		return (
			<Drawer id="nav-drawer" variant="persistent" open={this.state.show}>
				<div className="menu-links">
					<NavLink to="/favorites">
						<Icon>star</Icon> Favorites
					</NavLink>
					<NavLink to="/playlists">
						<Icon>playlist_play</Icon> Playlists
					</NavLink>
				</div>
			</Drawer>
		);
	}
}
